Data Science Bootcamp Assignment 2 \
Samridh Srivastava \
ss18906

In [18]:
import numpy as np
import pandas as pd


# Part 1 - Numpy

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [27]:
a = np.array([1,3,4,0])
b = np.array([4,3,2,1])

horizontalStack = np.hstack((a,b))
verticalStack = np.vstack((a,b))

print(horizontalStack)
print(verticalStack)


[1 3 4 0 4 3 2 1]
[[1 3 4 0]
 [4 3 2 1]]


2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]


In [28]:
intersection = np.intersect1d(a,b)
print(intersection)

[1 3 4]


⁠ Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [29]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

indices = np.where((A>=5) & (A<=10))
print(A[indices])

[ 5  6  7  8  9 10]


4. ⁠⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [25]:
filteredRows = iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0) ]
print(filteredRows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# Part 2 - Pandas

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).


In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [35]:
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
filtered_df

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.


In [37]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [38]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

df.head()

<ipython-input-38-aedc6f727fe1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-38-aedc6f727fe1>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

In [39]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df.head()

0   1   2   3
0  21  29  19  37
1  29  33  22  27
2  36  30  19  24
3  24  16  22  12
4  26  33  24  22

In [42]:
filtered_df = df[df.sum(axis=1) >100]
filtered_df

0   1   2   3
0   21  29  19  37
1   29  33  22  27
2   36  30  19  24
4   26  33  24  22
5   25  20  38  35
8   23  31  12  35
9   39  38  28  22
12  27  15  34  37